### ISSUE TITLE
SystemStackError error="stack level too deep"  with "ulimit -n" command is 65536

### ISSUE THREAD

**Issue by guhy1011** [wshihadeh/fluent-plugin-record-splitter#4]
I have tried this plugin [github.com/wshihadeh/fluent-plugin-record-splitter]. just followed the guide but got a problem:

```
2022-05-17 23:01:13 -0700 [warn]: #0 fluent/log.rb:351:warn: thread exited by unexpected error plugin=Fluent::Plugin::SampleInput title=:sample_input error_class=SystemStackError error="stack level too deep"
#<Thread:0x0000564c85d58ef0@sample_input@/usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2136: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
	2135: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin/in_sample.rb:98:in `run'
	2134: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin/in_sample.rb:113:in `emit'
	2133: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin/in_sample.rb:113:in `times'
	2132: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin/in_sample.rb:113:in `block in emit'
	2131: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/event_router.rb:106:in `emit'
	2130: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/event_router.rb:115:in `emit_stream'
	2129: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/plugin/output.rb:839:in `emit_sync'
	 ... 2124 levels...
	   4: from /usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/v14.rb:23:in `process'
	   3: from /usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/core.rb:47:in `process'
	   2: from /usr/local/share/gems/gems/fluentd-1.14.6/lib/fluent/event.rb:110:in `each'
	   1: from /usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/core.rb:49:in `block in process'
/usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/core.rb:49:in `select': stack level too deep (SystemStackError)
2022-05-17 23:01:13 -0700 [error]: #0 fluent/log.rb:372:error: unexpected error error_class=SystemStackError error="stack level too deep"
  2022-05-17 23:01:13 -0700 [error]: #0 fluent/supervisor.rb:971:main_process: /usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/core.rb:49:in `select'
  2022-05-17 23:01:13 -0700 [error]: #0 fluent/supervisor.rb:971:main_process: /usr/local/share/gems/gems/fluent-plugin-record-splitter-0.0.1/lib/fluent/plugin/out_record_splitter/core.rb:49:in `block in process'
```
and the following is my fluent.conf file, and when I check the existing configuration using the``` ulimit -n ```command is 65536 on my machine. I have no idea how to fix, does anyone have any solutions? thanks in advance.
```
<source>
  @type dummy
  tag dummy
  dummy {"akey":"c", "abkey":"cc", "message": "line one\nlines2" }
</source>

<match dummy>
  @type record_splitter
  tag dummy
  input_key message
  split_stratgey lines
  append_new_line true
  remove_new_line true
  shared_keys ["akey"]
</match>
```

**Comment by guhy1011** [comment]
fixed

**Comment by ashihadeh-boku** [comment]
what was the issue ?

**Comment by wshihadeh** [comment]
what was the issue ?

**Comment by guhy1011** [comment]
Hi wshihadeh, thanks for your respond, and I think it may be caused by the system issue or the conflict of other plugin. Anyway, it works well now.
